### ISSUE TITLE
The set resolution frame is not applied.

### ISSUE THREAD

**Issue by Hanel99** [macmillan333/techmania#20]
Settings - Graphics - Screen resolution does not apply to the selected frame.
Based on the RTX3070 graphic card, more than 2000 frames are overloaded on the graphic card.
please solve

(The content has been translated with Google Translate. Please understand.)

**Comment by macmillan333** [comment]
If you turn on VSync in options, frame rate will be locked and equal to refresh rate. Please try it.

**Comment by Hanel99** [comment]
Solved!
This was a simple problem. Thank you.
