### ISSUE TITLE
Make pattern backingTrack optional

### ISSUE THREAD

**Issue by rogeraabbccdd** [macmillan333/techmania#4]
`patternMetadata.backingTrack` is required to play track in editor.
It's a problem when porting songs from bms.
There's no something like backingtrack in bms. Background music is played by hidden notes.

**Comment by macmillan333** [comment]
It is optional. You can check the included tracks - all patterns in Etude and f for fun do not use a backing track.

**Comment by macmillan333** [comment]
Adding to that, when the game or editor does not work on a certain track, it may write error messages to the log. Check the contributing guidelines on how to retrieve and post these logs.
