### ISSUE TITLE
Use some archive format for tracks

### ISSUE THREAD

**Issue by samnyan** [macmillan333/techmania#8]
Unziping and copying note sounds were slow especially for mobile device. Packing all files to an archive will be way easier to transfer.
For example zip should be able to read just like a folder.

**Comment by macmillan333** [comment]
Acknowledged.

**Comment by macmillan333** [comment]
Added partial support for this in 0.6: game will now extract any zip archive it sees.
Due to how Unity loads external resources (with URIs), it doesn't seem possible to load a track directly from a zip, so I believe this is all I can do. Feel free to reopen if you have more suggestions.
